#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
make_sample_gcode.py —— 生成一个用于测试分析工具的样例 G 代码文件

为什么需要这个脚本
    没有真实 gcode 时仍需验证解析与换算逻辑是否正确。
    做法是构造一个"已知答案"的样例文件，再用分析器解析，
    将输出与手算预期值比对，从而定位换算系数或解析逻辑的错误。

样例文件包含三个已知量：
    - 每层挤出长度固定
    - 层数固定
    - 温度设定固定
    解析结果与手算值一致，即说明换算链路正确。
"""
from pathlib import Path
import sys

# ---- 样例参数（改这里可以生成不同的测试用例）----
LAYERS = 12           # 层数
PER_LAYER_E = 100.0   # 每层挤出多少 mm 耗材
LAYER_HEIGHT = 0.2    # 层高 mm
NOZZLE_TEMP = 210     # 喷嘴温度
BED_TEMP = 60         # 热床温度
FEEDRATE = 1800       # 进给速度 mm/min


def main():
    # 同 gcode_analyzer.py：Windows 控制台默认 GBK，先切 UTF-8 再打印中文
    try:
        sys.stdout.reconfigure(encoding="utf-8")
    except (AttributeError, ValueError):
        pass

    out = Path(__file__).with_name("sample.gcode")
    lines = []

    # ---------- 头部：切片软件通常写的元数据注释 ----------
    lines += [
        "; 这是一个用于测试 gcode_analyzer.py 的样例文件",
        "; generated by make_sample_gcode.py",
        "; printer_model = TestPrinter FDM",
        "; filament_type = PLA",
        f"; layer_height = {LAYER_HEIGHT}",
        "; nozzle_diameter = 0.4",
        "; 预计打印时间 1h 5m",     # 故意写个切片软件风格的时间注释
        "",
        "M82",                       # 绝对挤出模式
        f"M104 S{NOZZLE_TEMP}",      # 设定喷嘴温度（不等待）
        f"M140 S{BED_TEMP}",         # 设定热床温度
        f"M109 S{NOZZLE_TEMP}",      # 等待喷嘴到位
        f"M190 S{BED_TEMP}",         # 等待热床到位
        "G28 ; home all axes",
        "G90 ; absolute positioning",
        "G92 E0 ; 复位挤出机计数",
        "",
    ]

    e = 0.0  # 累计挤出量（绝对模式）
    for layer in range(LAYERS):
        z = round((layer + 1) * LAYER_HEIGHT, 2)
        lines.append(f";LAYER_CHANGE")
        lines.append(f";Z: {z}")
        lines.append(f"G1 Z{z} F600 ; 抬到第 {layer+1} 层")
        lines.append("M106 S255 ; 风扇全开")

        # 每层走 4 条边（一个正方形），每条边挤出 PER_LAYER_E/4
        per_seg = PER_LAYER_E / 4.0
        side = 20.0  # 正方形边长 mm
        e += per_seg
        lines.append(f"G1 X{side:.2f} Y0 E{e:.3f} F{FEEDRATE}")
        e += per_seg
        lines.append(f"G1 X{side:.2f} Y{side:.2f} E{e:.3f}")
        e += per_seg
        lines.append(f"G1 X0 Y{side:.2f} E{e:.3f}")
        e += per_seg
        lines.append(f"G1 X0 Y0 E{e:.3f}")

        # 一段空驶（不挤出），用来验证空驶路径统计
        lines.append("G0 X10 Y10 F6000 ; 空驶")
        lines.append("")

    # ---------- 结尾 ----------
    lines += [
        "M104 S0 ; 关喷嘴加热",
        "M140 S0 ; 关热床加热",
        "M106 S0 ; 关风扇",
        "G28 X Y ; 归位",
        "M84 ; 关步进电机",
    ]

    out.write_text("\n".join(lines) + "\n", encoding="utf-8")

    expected = {
        "层数": LAYERS,
        "总挤出长度(mm)": LAYERS * PER_LAYER_E,
        "喷嘴温度(°C)": NOZZLE_TEMP,
        "热床温度(°C)": BED_TEMP,
    }
    print(f"[已生成] {out}")
    print("预期分析结果（用来校验分析工具）：")
    for k, v in expected.items():
        print(f"    {k}: {v}")


if __name__ == "__main__":
    main()
